apiVersion: v1
kind: Service
metadata:
  name: {{ include "website-stack.fullname" . }}-frontend
spec:
  selector:
    app.kubernetes.io/name: website-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
